using Microsoft.ML.Data;

namespace TaxiMo.Services.MLModels
{
    /// <summary>
    /// Prediction result from the ML regression model.
    /// Contains the predicted preference score for a driver candidate.
    /// </summary>
    public class DriverPrediction
    {
        /// <summary>
        /// Predicted preference score for the driver (higher = better match).
        /// This score is generated by the SDCA regression model and represents how well the driver
        /// matches the user's historical preferences based on learned patterns from past rides.
        /// Scores are typically in the range [0, 1] (normalized) but can extend beyond due to regression.
        /// </summary>
        [ColumnName("Score")]
        public float PredictedScore { get; set; }
    }
}
